spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/auth/realms/one
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
